language: php

sudo: true

php:
  - 7.0
  - 7.1

addons:
    apt:
        packages:
            - apache2
            - oracle-java8-set-default

before_script:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
    - sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl -v http://localhost:9200/
    - phpenv config-rm xdebug.ini
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "zend.enable_gc = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

    - cp app/config/parameters.yml.travis app/config/parameters.yml

    - composer self-update
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then composer install --no-interaction --prefer-dist; fi;
    - php app/console cache:clear --env=test

    - php app/console wellcommerce:install
    - php app/console cache:warmup --env=test

script:
    - phpunit -c phpunit.xml.dist
    - bin/security-checker security:check composer.lock

notifications:
    email: false
    slack: wellcommerce:5g1PqYtrlI40NVxaiuFzeG9z
