language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  - CONTRIBUTOR=1
  - CONTRIBUTOR=0

services:
  - elasticsearch

addons:
    apt:
        packages:
            - apache2

before_script:
    - sleep 10
    - phpenv config-rm xdebug.ini
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "zend.enable_gc = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

    - mysql -e 'CREATE DATABASE travis;'
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - if [[ $CONTRIBUTOR = 1 ]] ; then wget https://gist.githubusercontent.com/adampiotrowski/2300cf0b6b953cb0897f753254d9eb66/raw/929b817a6ac02e07420dc11a5e2a98527677f25b/contributor.sh; fi;

    - composer self-update
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then composer install --no-interaction --prefer-dist; fi;
    - composer dump-autoload
    - php app/console cache:clear --env=test

    - php app/console wellcommerce:app:install
    - php app/console cache:warmup --env=test

    - wget http://get.sensiolabs.org/security-checker.phar

script:
    - phpunit -c phpunit.xml.dist
    - php security-checker.phar security:check composer.lock

notifications:
    email: false
    slack: wellcommerce:5g1PqYtrlI40NVxaiuFzeG9z
